name: ci

on:
  push:
    branches: [main]
    paths-ignore:
      - '**.md'
      - 'LICENSE'
      - '.gitignore'
      - '.github/**'
  pull_request:
    branches: [main]
    paths-ignore:
      - '**.md'
      - 'LICENSE'
      - '.gitignore'
      - '.github/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Clone fuibase
        run: git clone https://github.com/Incipe-win/fuibase.git ../fuibase

      - name: Setup xmake
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest

      - name: Install deps
        run: sudo apt-get update && sudo apt-get install -y g++

      - name: Build
        run: xmake f -m release && xmake

      - name: Test (help)
        run: ./dotrix help
